### ISSUE TITLE
Unable to use syntax 

### ISSUE THREAD

**Issue by omprakashomi** [vikrantyadav611/tail-animista#1]
I am unable to use after implement these code 
`module.exports = {
    theme: {
        extend: {
            animation: {
                "rotate-in-center": "rotate-in-center 0.6s cubic-bezier(0.250, 0.460, 0.450, 0.940)   both"
            },
            keyframes: {
                "rotate-in-center": {
                    "0%": {
                        transform: "rotate(-360deg)",
                        opacity: "0"
                    },
                    to: {
                        transform: "rotate(0)",
                        opacity: "1"
                    }
                }
            }
        }
    }
}`.

Kindly suggest me how to use these one.
I am using `rotate-in-center` in class but nothing showing.

**Comment by vikrantyadav611** [comment]
@omprakashomi Please make sure to use animate prefix while using animation utilities, in your case it should be `animate-rotate-in-center`  in class property

**Comment by omprakashomi** [comment]
Okay

I will use

**Comment by vikrantyadav611** [comment]
Leaving the link to the documentation to animation utility for better understanding as well as closing the ticket
https://tailwindcss.com/docs/animation
